export const easyWords = [
  {word: "cat", sentence: "The happy cat chased the little mouse."},
  {word: "ball", sentence: "The big red ball rolled down the hill."},
  {word: "bird", sentence: "The small bird sang a sweet song."},
  {word: "rabbit", sentence: "The fast rabbit hopped across the grass."},
  {word: "tree", sentence: "The tall tree swayed in the gentle breeze."},
  {word: "car", sentence: "The shiny car zoomed down the street."},
  {word: "puppy", sentence: "The cute puppy played with a colorful toy."},
  {word: "sun", sentence: "The bright sun shone in the clear sky."},
  {word: "dolphin", sentence: "The friendly dolphin jumped in the blue ocean."},
  {word: "kitten", sentence: "The playful kitten pounced on the soft pillow."},
  {word: "dog", sentence: "The dog barks loudly at night."},
  {word: "cow", sentence: "A cow gives us fresh milk to drink."},
  {word: "lion", sentence: "The lion has a big, fluffy mane."},
  {word: "tiger", sentence: "The tiger has orange fur with black stripes."},
  {word: "elephant", sentence: "An elephant has a long trunk to drink water."},
  {word: "bear", sentence: "A bear likes to eat honey from the hive."},
  {word: "horse", sentence: "The horse runs fast across the field."},
  {word: "monkey", sentence: "A monkey swings from tree to tree."},
  {word: "fish", sentence: "A fish swims in the cool water."},
  {word: "sheep", sentence: "The sheep has soft, woolly fur."},
  {word: "chicken", sentence: "The chicken has soft feathers and lives on the farm."},
  {word: "fox", sentence: "The fox is clever and quick."},
  {word: "wolf", sentence: "A wolf howls at the moon at night."}
]

export const mediumWords = [
    { word: "shirt", sentence: "The shirt has bright red stripes." },
    { word: "pants", sentence: "My pants have pockets on the sides." },
    { word: "jacket", sentence: "I wear a jacket when it’s cold outside." },
    { word: "dress", sentence: "She wore a dress with pretty flowers." },
    { word: "skirt", sentence: "The skirt is twirly and fun to wear." },
    { word: "sweater", sentence: "A cozy sweater keeps me warm." },
    { word: "socks", sentence: "I put on my socks before my shoes." },
    { word: "shoes", sentence: "My shoes make a tapping sound when I walk." },
    { word: "hat", sentence: "A hat keeps the sun out of my eyes." },
    { word: "scarf", sentence: "I wrap a scarf around my neck in winter." },
    { word: "gloves", sentence: "My gloves keep my hands warm." },
    { word: "belt", sentence: "The belt keeps my pants from falling down." },
    { word: "shorts", sentence: "I wear shorts when it’s hot outside." },
    { word: "coat", sentence: "A thick coat is good for snowy days." },
    { word: "boots", sentence: "My boots splash in the puddles." },
    { word: "t-shirt", sentence: "I wear a T-shirt on warm days." },
    { word: "pizza", sentence: "Pizza is delicious to enjoy with friends." },
    { word: "orange", sentence: "An orange is sweet and juicy." },
    { word: "bread", sentence: "Bread is perfect for making toast." },
    { word: "carrot", sentence: "Carrots are crunchy and orange." },
    { word: "cheese", sentence: "Cheese tastes wonderful in a sandwich." },
    { word: "rice", sentence: "We have rice with our dinner." },
    { word: "banana", sentence: "A banana is a snack I can peel myself." },
    { word: "salad", sentence: "Salad is full of fresh vegetables." }
  ];  


export const hardWords = [
    { word: 'kind', sentence: 'She is kind and shares her toys with friends.' },
    { word: 'brave', sentence: 'The brave girl tried the tall slide at the park.' },
    { word: 'happy', sentence: 'I feel happy when I play with my friends.' },
    { word: 'smart', sentence: 'He is smart and loves to solve puzzles.' },
    { word: 'funny', sentence: 'My friend tells funny jokes that make me laugh.' },
    { word: 'strong', sentence: 'The strong boy carries his heavy backpack.' },
    { word: 'gentle', sentence: 'Be gentle with the baby kitten.' },
    { word: 'friendly', sentence: 'A friendly smile makes people feel good.' },
    { word: 'curious', sentence: 'She is curious and asks many questions.' },
    { word: 'helpful', sentence: 'The helpful boy carries groceries for his mom.' },
    { word: 'quiet', sentence: 'We need to be quiet in the library.' },
    { word: 'silly', sentence: 'The silly clown made us all laugh.' },
    { word: 'honest', sentence: 'It is important to be honest and tell the truth.' },
    { word: 'caring', sentence: 'The caring girl helps her brother when he falls.' },
    { word: 'creative', sentence: 'He is creative and loves to draw pictures.' },
    { word: 'patient', sentence: 'She is patient and waits her turn in line.' },
    { word: 'cheerful', sentence: 'The cheerful song lifted everyone\'s spirits.' },
    { word: 'thoughtful', sentence: 'He is thoughtful and remembers my birthday.' },
    { word: 'determined', sentence: 'She is determined to finish the race.' },
    { word: 'playful', sentence: 'The playful puppy loves to chase its tail.' },
    { word: 'respectful', sentence: 'He is respectful and listens to his teachers.' },
    { word: 'imaginative', sentence: 'Her imaginative stories take us to magical places.' },
    { word: 'teacher', sentence: 'The teacher reads us fun stories in class.' },
    { word: 'doctor', sentence: 'The doctor gives us check-ups to keep us healthy.' },
    { word: 'engineer', sentence: 'The engineer designs cool buildings and bridges.' },
    { word: 'artist', sentence: 'The artist paints beautiful pictures that hang in the gallery.' },
    { word: 'chef', sentence: 'The chef makes yummy pizza that we can eat for lunch.' },
    { word: 'firefighter', sentence: 'The firefighter rushes to help when there is a fire.' },
    { word: 'nurse', sentence: 'The nurse gives us band-aids when we get hurt.' },
    { word: 'scientist', sentence: 'The scientist does experiments to learn about the world.' },
    { word: 'writer', sentence: 'The writer creates amazing stories that take us on adventures.' },
    { word: 'lawyer', sentence: 'The lawyer helps people understand their rights.' },
    { word: 'musician', sentence: 'The musician plays cheerful songs that make us want to dance.' }
  ]

export const finalWords = [
    { word: "optimistic", sentence: "The optimistic girl always hopes for the best." },
    { word: "compassionate", sentence: "He is compassionate and helps others feel better." },
    { word: "adventurous", sentence: "The adventurous boy loves to climb trees and explore." },
    { word: "confident", sentence: "She is confident and speaks in front of the class." },
    { word: "reliable", sentence: "My reliable friend always comes to play on time." },
    { word: "independent", sentence: "The independent girl likes to tie her shoes by herself." },
    { word: "ambitious", sentence: "He is ambitious and wants to be a doctor one day." },
    { word: "humble", sentence: "The humble boy shares his toys without bragging." },
    { word: "generous", sentence: "She is generous and gives her extra crayons to friends." },
    { word: "resilient", sentence: "The resilient girl keeps trying, even when it's hard." },
    { word: "loyal", sentence: "A loyal friend sticks by you when things get tough." },
    { word: "creative", sentence: "He is creative and makes beautiful drawings." },
    { word: "diligent", sentence: "The diligent student always finishes her homework on time." },
    { word: "patient", sentence: "She is patient and waits for her turn to speak." },
    { word: "thoughtful", sentence: "A thoughtful friend remembers to ask how you feel." },
    { word: "resourceful", sentence: "He is resourceful and finds ways to solve problems." },
    { word: "math", sentence: "Math helps us learn how to add and subtract numbers." },
    { word: "science", sentence: "Science teaches us about plants, animals, and the Earth." },
    { word: "english", sentence: "In English class, we read stories and write our own." },
    { word: "history", sentence: "History shows us how people lived a long time ago." },
    { word: "art", sentence: "Art is fun because we get to paint and create pictures." },
    { word: "music", sentence: "In music class, we sing songs and learn about instruments." }
  ]
  